/* This file is auto-generated by scripts/generate-original-themes-artifacts.mjs. */

export const ORIGINAL_THEMES_SOURCE_MANIFEST_FILE = "src/features/popover/styles/original-themes/manifest.json" as const;
export const ORIGINAL_THEMES_SOURCE_MANIFEST_SHA256 = "b3324eb570b62d208adcbb0612d169831d82a99e429777062efa540a4d64cb41" as const;

export const ORIGINAL_THEMES_THEME_ORDER = [
  "basic",
  "pro",
  "creative",
  "galaxy",
  "neon",
  "cyberpunk",
  "aurora"
] as const;

export const ORIGINAL_THEMES_SHARED_SLICE_FILES = [
  "shared/part-01.css",
  "shared/part-02.css",
  "shared/part-03.css",
  "shared/part-04.css",
  "shared/part-05.css",
  "shared/part-06.css",
  "shared/part-07.css",
  "shared/part-08.css",
  "shared/part-09.css"
] as const;

export const ORIGINAL_THEMES_THEME_CATEGORY_ORDER = {
  "basic": [
    "tokens",
    "trigger",
    "panels",
    "effects"
  ],
  "pro": [
    "tokens",
    "trigger",
    "panels",
    "effects"
  ],
  "creative": [
    "tokens",
    "trigger",
    "panels",
    "effects"
  ],
  "galaxy": [
    "tokens",
    "effects",
    "trigger",
    "panels",
    "effects"
  ],
  "neon": [
    "tokens",
    "effects",
    "panels",
    "effects",
    "trigger"
  ],
  "cyberpunk": [
    "tokens",
    "effects",
    "trigger",
    "panels",
    "effects"
  ],
  "aurora": [
    "tokens",
    "effects",
    "panels",
    "effects",
    "trigger"
  ]
} as const;

export const ORIGINAL_THEMES_THEME_SLICE_FILES = {
  "basic": [
    "themes/basic/tokens/part-01.css",
    "themes/basic/trigger/part-01.css",
    "themes/basic/panels/part-01.css",
    "themes/basic/effects/part-01.css"
  ],
  "pro": [
    "themes/pro/tokens/part-01.css",
    "themes/pro/trigger/part-01.css",
    "themes/pro/panels/part-01.css",
    "themes/pro/effects/part-01.css"
  ],
  "creative": [
    "themes/creative/tokens/part-01.css",
    "themes/creative/trigger/part-01.css",
    "themes/creative/panels/part-01.css",
    "themes/creative/effects/part-01.css"
  ],
  "galaxy": [
    "themes/galaxy/tokens/part-01.css",
    "themes/galaxy/effects/part-01.css",
    "themes/galaxy/trigger/part-01.css",
    "themes/galaxy/panels/part-01.css",
    "themes/galaxy/effects/part-02.css",
    "themes/galaxy/effects/part-03.css"
  ],
  "neon": [
    "themes/neon/tokens/part-01.css",
    "themes/neon/effects/part-01.css",
    "themes/neon/panels/part-01.css",
    "themes/neon/effects/part-02.css",
    "themes/neon/trigger/part-01.css"
  ],
  "cyberpunk": [
    "themes/cyberpunk/tokens/part-01.css",
    "themes/cyberpunk/effects/part-01.css",
    "themes/cyberpunk/trigger/part-01.css",
    "themes/cyberpunk/panels/part-01.css",
    "themes/cyberpunk/effects/part-02.css",
    "themes/cyberpunk/effects/part-03.css",
    "themes/cyberpunk/effects/part-04.css"
  ],
  "aurora": [
    "themes/aurora/tokens/part-01.css",
    "themes/aurora/effects/part-01.css",
    "themes/aurora/panels/part-01.css",
    "themes/aurora/effects/part-02.css",
    "themes/aurora/trigger/part-01.css"
  ]
} as const;

export const ORIGINAL_THEME_SLICE_FILES = [
  "shared/part-01.css",
  "shared/part-02.css",
  "shared/part-03.css",
  "shared/part-04.css",
  "shared/part-05.css",
  "shared/part-06.css",
  "shared/part-07.css",
  "shared/part-08.css",
  "shared/part-09.css",
  "themes/basic/tokens/part-01.css",
  "themes/basic/trigger/part-01.css",
  "themes/basic/panels/part-01.css",
  "themes/basic/effects/part-01.css",
  "themes/pro/tokens/part-01.css",
  "themes/pro/trigger/part-01.css",
  "themes/pro/panels/part-01.css",
  "themes/pro/effects/part-01.css",
  "themes/creative/tokens/part-01.css",
  "themes/creative/trigger/part-01.css",
  "themes/creative/panels/part-01.css",
  "themes/creative/effects/part-01.css",
  "themes/galaxy/tokens/part-01.css",
  "themes/galaxy/effects/part-01.css",
  "themes/galaxy/trigger/part-01.css",
  "themes/galaxy/panels/part-01.css",
  "themes/galaxy/effects/part-02.css",
  "themes/galaxy/effects/part-03.css",
  "themes/neon/tokens/part-01.css",
  "themes/neon/effects/part-01.css",
  "themes/neon/panels/part-01.css",
  "themes/neon/effects/part-02.css",
  "themes/neon/trigger/part-01.css",
  "themes/cyberpunk/tokens/part-01.css",
  "themes/cyberpunk/effects/part-01.css",
  "themes/cyberpunk/trigger/part-01.css",
  "themes/cyberpunk/panels/part-01.css",
  "themes/cyberpunk/effects/part-02.css",
  "themes/cyberpunk/effects/part-03.css",
  "themes/cyberpunk/effects/part-04.css",
  "themes/aurora/tokens/part-01.css",
  "themes/aurora/effects/part-01.css",
  "themes/aurora/panels/part-01.css",
  "themes/aurora/effects/part-02.css",
  "themes/aurora/trigger/part-01.css"
] as const;

export type OriginalThemesThemeId = (typeof ORIGINAL_THEMES_THEME_ORDER)[number];
export type OriginalThemesCategory = (typeof ORIGINAL_THEMES_THEME_CATEGORY_ORDER)[OriginalThemesThemeId][number];
